# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Release Angular App

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    - name: Create tag
      id: tag_version
      run: |
        TAG_NAME=v$(date +'%Y%m%d%H%M%S')
        echo "::set-output name=TAG_NAME::$TAG_NAME"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.TAG_NAME }}
        release_name: Release ${{ steps.tag_version.outputs.TAG_NAME }}
        body: |
          ## Commits
          ${{ github.event.pull_request.body }}
        draft: false
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist
        asset_name: source_code.zip
        asset_content_type: application/zip


      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ steps.version.outputs.content }}
      #     release_name: Build ${{ steps.version.outputs.content }}
      #     body: |
      #       This is the release description for Build ${{ steps.version.outputs.content }}.
      #       You can add more details here.

      #       **Latest Commit:**
      #       $(git log --pretty=format:'- %s' -n 1 HEAD)

      #     draft: false
      #     prerelease: false

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     path: dist
      #     token: ${{ secrets.GITHUB_TOKEN  }}
      #     commit: ${{ github.sha }}
      #     tag: ${{ steps.version.outputs.content }}

      # - name: Deploy
      #   run: |
      #     npm install
      #     npm run-script deploy
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: dist/angular-shop
