name: Angular Build, Tag and Release

on:
  pull_request:
    branches: [main]

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Extract base version
        id: extract_version
        run: |
          base_version=$(echo "${{ steps.gitversion.outputs.nuGetVersion }}" | sed -E 's/[^0-9.]+//g')
          echo "::set-output name=base_version::$base_version"
      - name: Create version.txt with base version
        run: echo "${{ steps.extract_version.outputs.base_version }}"


  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - run: npm ci
      - run: npm run build

      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2

      - name: Get last commit message
        id: last_commit
        run: echo "LAST_COMMIT=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  v${{ steps.extract_version.outputs.base_version }}
          release_name: "Build v${{ steps.extract_version.outputs.base_version }}"
          body: |
            **🚀 New Release Published!**
            * **Repository:** ${{ github.repository }}
            * **Release Name:** ${{ github.event.release.name }}
            * **Author:** ${{ github.actor }}
            * **Commit:** ${{ github.sha }}
            * **Commit message 2:** ${{ github.event.commits[0].message }}
            * **Latest Commit 3:** ${{ env.LAST_COMMIT }}
            * **Link:** ${{ github.server_url }}/{{ github.repository }}/releases/tag/${{ github.ref  || 'latest' }}

          draft: true
          prerelease: false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

  send_notification:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send Telegram message
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.CHAT_ID }}&text=**🚀 New Release Published!**
            * **Repository:** ${{ github.repository }}
            * **Release Name:** ${{ github.event.release.name }}
            * **Author:** ${{ github.actor }}
            * **Commit:** ${{ github.sha }}
            * **Commit message 2:** ${{ github.event.commits[0].message }}
            * **Latest Commit 3:** ${{ env.LAST_COMMIT }}
            * **Link:** ${{github.server_url}}/{{github.repository}}/releases/tag/${{github.ref || 'latest' }}"
