name: Telegram Notification on Release or Main Update

on:
  release:
    types: [published]
  pull_request:
    branches: [main]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.CHAT_ID }}&text=**🚀 New Release Published!**
            * **Repository:** ${{ github.repository }}
            * **Release Name:** ${{ github.event.release.name }}
            * **Tag:** ${{ github.event.release.tag_name }}
            * **Author:** ${{ github.actor }}
            * **Commit:** ${{ github.sha }}
            * **Commit message2:** ${{ github.event.commits[0].message }}
            * **Link:** ${{ github.server_url }}/{{ github.repository }}/releases/tag/${{ github.ref_name  || 'latest' }}"
