name: Telegram Notification on Release or Main Update

on:
  push:
    branches: [main]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.CHAT_ID }}&text=**New release created!**"
